name: build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots test jacoco:report-aggregate coveralls:report -DpullRequest=${{ github.event.pull_request.number }} -DrepoToken=${{ secrets.COVERALLS_TOKEN }}
      working-directory: ./parent
    - uses: actions/upload-artifact@v2
      with:
        name: jacoco.xml
        path: /home/runner/work/public_act/public_act/parent/apps/target/site/jacoco-aggregate/jacoco.xml
